insert into categoria (cat_nombre,cat_foto,cat_descripcion) values('CDU',null,'centro deportivo tulcan');
insert into categoria (cat_nombre,cat_foto,cat_descripcion) values('DIAMANTE',null,'centro deportivo el diamante');
insert into categoria (cat_nombre,cat_foto,cat_descripcion) values('DIAMANTE2',null,'centro deportivo el diamante');
insert into categoria (cat_nombre,cat_foto,cat_descripcion) values('DIAMANTE3',null,'centro deportivo el diamante');
insert into categoria (cat_nombre,cat_foto,cat_descripcion) values('DIAMANTE4',null,'centro deportivo el diamante');
insert into categoria (cat_nombre,cat_foto,cat_descripcion) values('DIAMANTE5',null,'centro deportivo el diamante');
insert into categoria (cat_nombre,cat_foto,cat_descripcion) values('DIAMANTE6',null,'centro deportivo el diamante');
insert into categoria (cat_nombre,cat_foto,cat_descripcion) values('DIAMANTE7',null,'centro deportivo el diamante');
insert into categoria (cat_nombre,cat_foto,cat_descripcion) values('DIAMANTE8',null,'centro deportivo el diamante');
insert into categoria (cat_nombre,cat_foto,cat_descripcion) values('DIAMANTE9',null,'centro deportivo el diamante');
insert into escenario (esc_nombre,esc_descripcion,esc_foto,esc_estado,cat_nombre) values('CANCHA 1',' descripcion de la cancha 1', null,'0','CDU');